### ISSUE TITLE
Create the absolute theory

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#103]
Rather than s trimming as proposed in #61 (or together with a trimming of unnecessary information). Let's define here in `pineko` the absolute theory. As discussed during this Wednesday code meeting, there is nothing in n3fit/vp that uses the theory card that is not used also by `pineko` (PTO being the only thing that is _actually_ used but as mentioned, the order needs to be known by pineko to create the fktables/eko).

Once we have an absolute theory we just swap the one in the nnpdf repository for whatever we decide here.

**Comment by AleCandido** [comment]
This is not incompatible with #61, since the goal of #61 is actually to split the different theories out of the *absolute* theory (it was simply assuming that the current NNPDF theory format is already the *absolute one)

```mermaid
flowchart LR
    abs(Absolute theory)
    eko(EKO theory)
    pf(pinefarm theory)
    abs --> eko
    abs --> pf
```

However, since the theory is mostly Evolution + DIS, the main goals are:
1. complete porting the EKO theories https://github.com/NNPDF/eko/issues/248
2. move yadism theories to an analogue format of EKO (finding out which arguments we actually need)
3. check if we want to add other parameters to the pinefarm theory, to serve Vrap, Madgraph, and Matrix @cschwan

**Comment by felixhekhorn** [comment]
> 3\. check if we want to add other parameters to the pinefarm theory, to serve Vrap, Madgraph, and Matrix @cschwan

see https://github.com/NNPDF/pinefarm/issues/1

**Comment by felixhekhorn** [comment]
This is also a further step in coupling pineko and pinefarm tighter together (as Numerical FONLL is doing cc @RoyStegeman ).
This decision is reasonable, but we should be aware of it.

**Comment by AleCandido** [comment]
> This is also a further step in coupling pineko and pinefarm tighter together

Well, it's not really *together*, since the connection is asymmetric: as usual, it's Pineko that has to know things, while Pinefarm is only driven by, and will keep ignoring what's in the rest of the world.

**Comment by scarlehoff** [comment]
This is now happening in https://github.com/NNPDF/nnpdf/pull/2028 so I'll close it from here
