### ISSUE TITLE
Drop `yamldb` as default

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/pineko#156]
We should drop the usage of `yamldb` as default,  in favor of `validphys` once:

https://github.com/NNPDF/nnpdf/pull/1942

is merged. But we can keep the possibility to use `yamldb`.

**Comment by alecandido** [comment]
I'd say that, for the sake of maintenance, there should be only one way to do things, to tame complexity.

If you need an easy way to patch it, that should be provided by `vp` (or the VP->Pineko interface).

**Comment by Radonirinaunimi** [comment]
> I'd say that, for the sake of maintenance, there should be only one way to do things, to tame complexity.
> 
> If you need an easy way to patch it, that should be provided by `vp` (or the VP->Pineko interface).

But I think this is a big issue for external users. External users should not have to implement vp-commondata in order to just generate predictions. So still allowing for the `yamldb` would alleviate this.

**Comment by alecandido** [comment]
First, there are not many external users for Pineko, since its only goal is to deal with FkTables.

Then, I'd say that not all of the vp-commondata should be required for Pineko, so you could trim them to a minimal specification.

If you want to use Pineko w/ and w/o `vp`, the best would be that Pineko states an interface, and this interface (by chance :P) is also implemented by vp-commondata.

@scarlehoff

**Comment by scarlehoff** [comment]
@comane will be in charge of creating a commondata/theory package out of vp with only the parser so that it can be used for pineko, for the gaussian process, etc.

**Comment by alecandido** [comment]
Ok, but it will be the same one used in `vp`, isn't it?
