### ISSUE TITLE
`kfactor` module maintenance 

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/pineko#160]
we should maintain the `kfactor` module, right now it isn't documented, variables names are not consistent (`max_as` should look somenting as `order_to_update`) , and there are some hardcoded pieces which most likely will not work anymore with the new commondata: 

https://github.com/NNPDF/pineko/blob/06458035efaa06e5236acdd07cffde12afa2bfe6/src/pineko/kfactor.py#L401-L403

**Comment by alecandido** [comment]
Btw: a huge rework, that could simplify it a lot, is now possible because of `merge` support in PineAPPL:
https://github.com/NNPDF/pineappl/pull/247

This was not available at the time this module was written (same for scale variations), and because of this many files were generated and later merged.
Ok, PineAPPL subgrids are not NumPy arrays, so not all operations are available. But indexing, scalar multiplications and a combination of sum/concatenation (through merge) is. This should be enough to reimplement it as:
- collect weights and paths (from here to there times this)
- apply the operation in memory

**Comment by giacomomagni** [comment]
Yes indeed that we can also benefit. 
But also other pieces can be simplified:

https://github.com/NNPDF/pineko/blob/06458035efaa06e5236acdd07cffde12afa2bfe6/src/pineko/kfactor.py#L115-L121

for instace here `m` is subtracted and added back, so can simply be dropped by the function.

**Comment by alecandido** [comment]
There are also entire functions to:
- extract the subgrid to a NumPy array
- scale the array
- set the scaled array as a new subgrid

https://github.com/NNPDF/pineko/blob/06458035efaa06e5236acdd07cffde12afa2bfe6/src/pineko/kfactor.py#L124-L145

While instead you could directly scale the subgrid itself
https://github.com/NNPDF/pineappl/blob/e0a45f6107befb63e25164c91244eb669b1bcfe1/pineappl_py/src/subgrid.rs#L202-L204

**Comment by giacomomagni** [comment]
@alecandido do you remember what happen in case of merging with an overlapping order ?
It's simply overwritten?

**Comment by alecandido** [comment]
Not really, the two subgrids will get merged.

The `Grid.merge()` algorithm is simple: if there is only one, pick that, if there are two, call `Subgrid.merge()`.

Merging subgrids has a different meaning for each subgrid kind, but the overall idea is an addition (e.g. for the n-tuple means concatenating the tuples' lists, and for Lagrange should be actual addition of the weights).
