### ISSUE TITLE
Don't generate intermediate theory cards for nfonll

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#177]
With the new interface for nfonll, the user doesn't really need to run the different theories separately. I believe it would reduce friction to not generate the theory files (or to generate in the go as /tmp files) when running the ekos or fks command.

Note that thanks to #171 the theory information is saved in the fktable so the information about the theory the partial fktables were generated with is not lost.

I put the label enhancement, but maybe there's a good reason we want those files hanging around.

**Comment by felixhekhorn** [comment]
This is not possible, because we need those theory cards in `pinefarm` to generate the separate grids.

As was already discussed among the nfonll authors, this is a delicate issue - but I'm still convinced we should keep pinefarm and pineko as much decoupled as we can (or else we end up with a chimera again). Nfonll is explicitly playing on both fields and so we have the structure: pineko -> pinefarm -> pineko - see also https://github.com/NNPDF/papers/blob/master/num_fonll/figures/pineline_schematic.png The Amsterdam group (meaning @giacomomagni and @toonhasenack ) built an overarching structure to smoothen the workflow and we agreed to expose that at some point (though no progress was made on this so far). The correct place for such a thing is the `pineline` package.

**Comment by scarlehoff** [comment]
> This is not possible, because we need those theory cards in pinefarm to generate the separate grids.

But once you have the grids, these can be used with many different theories right?

**Comment by felixhekhorn** [comment]
> > This is not possible, because we need those theory cards in pinefarm to generate the separate grids.
> 
> But once you have the grids, these can be used with many different theories right?

as usual: by all "theories" (in the NNPDF sense) which have compatible settings, i.e. which only differ by settings which have no impact on grids (e.g. evolution settings). The "compatibility function" $c: [tcard, tcard] \to True \lor False$ is non-trivial.

**Comment by scarlehoff** [comment]
But this is also true for non-nfonll theories.
In any case, I've added the keys to the NNPDF theory card so this can be closed as an issue. I do think this would be an enhancement but I'm coming to nfonll just as an (sporadic) user so I'd rather stay on my lane here.
