### ISSUE TITLE
Decrease the default size of the `xgrid`

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#42]
100 points per fktable makes the fit too heavy. We should reduce it to 50 (or even less points if possible, old fktables got down to 20-30).

**Comment by scarlehoff** [comment]
Another interesting point is that it would be nice to have a low-precision version of `theory 400` with a very small number of points (say 5 per grid) so that it can be used in tests in CI.

**Comment by felixhekhorn** [comment]
How would we do this in practice?
- do we replace 400? or do we add a new theory? for the low precision version for sure we would add, right?
- how do we determine the number of sufficient points? I mean we compute a second version and then compare the two, fine, but do we do this for all 4k data points? because we would need to know which datasets are sensitive to which x region and make sure we cover them all
- we just recompute ekos, right? i.e. we reuse the grids as they are (some of them we can not even regenerate) and use only the interpolation of eko to a smaller grid (actually, with little effort and https://github.com/N3PDF/eko/pull/105 in place we could even avoid recomputing all together, since eko can in principle even interpolate as a post-process, i.e. on existing data)
- for the distribution we would still use [the PineAPPL formula](https://github.com/N3PDF/eko/blob/01efee1d27d215e895dd055debff8905af3d548c/src/eko/interpolation.py#L663), I guess?
- consider the [comment about interpolation](https://eko.readthedocs.io/en/latest/theory/Interpolation.html#change-interpolation-basis): in order to minimize further interpolation errors we concluded at some point that the new and the old grid share as many points as possible

**Comment by cschwan** [comment]
@felixhekhorn did you try using the 50 PineAPPL x-points in the output FK tables?

**Comment by scarlehoff** [comment]
For the low precision we do add (is the test theory).

I would keep this 400 as it is and create a new one (where for instance FTDY is NNLO).

About the points, honestly the best thing would be you give me a th 400 with 50 points instead and I benchmark it. If it works just the same we try to go a bit lower. A few steps and we are done.

Recreating all fktables would be basically a bash script right (if you give me such a script I'll do the different tests myself).

**Comment by felixhekhorn** [comment]
> @felixhekhorn did you try using the 50 PineAPPL x-points in the output FK tables?

@cschwan hm? how you mean "try"? in principle we can run pineko with any number of points ...

**Comment by felixhekhorn** [comment]
A practical limitation is the current pineko design: because pineko currently assumes a global `operator_card_template`: https://github.com/N3PDF/pineko/blob/707f21fba8d3715b68cc6ad4371229db84acdded/pineko.debug.toml#L6
- which defines the `interpolation_xgrid` which is the internal grid used to compute all operators
- but it could even hold a `inputgrid`, which instead defines the grid exposed to the fit (consider that for eko input=fitting scale)
- I guess we should change this design to make the template theory dependent, i.e. scope it by the theory id as all the other stuff

**Comment by cschwan** [comment]
@felixhekhorn to me the most natural way would be to choose the same x-grid everywhere. What was the reason for using 100 points instead?

**Comment by scarlehoff** [comment]
> What was the reason for using 100 points instead?

I asked for it to remove possible sources of errors during the benchmark

> the most natural way would be to choose the same x-grid everywhere

Not sure whether it will be actually useful neyond the low-precision theory (and there also the ekos can be low-prec) but outputing fktables of different sizes seems a hood thing.

**Comment by AleCandido** [comment]
> the most natural way would be to choose the same x-grid everywhere

I also believe it to be the most sensible choice, and it would be helpful in other contexts as well :)

**Comment by AleCandido** [comment]
@felixhekhorn @andreab1997 what is the status of this?

Are we using 50 points for the new ones? 
1. if yes, maybe we can close this
2. if no, maybe we can start doing it, and then do 1. :)

**Comment by andreab1997** [comment]
> @felixhekhorn @andreab1997 what is the status of this?
> 
> Are we using 50 points for the new ones?
> 
> 1. if yes, maybe we can close this
> 2. if no, maybe we can start doing it, and then do 1. :)

Yes, our default x-grid for the operators_cards contains 50 points now and I am computing the new fks with that.

**Comment by AleCandido** [comment]
So, I guess we can close this @scarlehoff @felixhekhorn

**Comment by andreab1997** [comment]
> So, I guess we can close this @scarlehoff @felixhekhorn

I don't know, do we want to address also the xgrid for testing stuff? Because, as far as I have understood, we only have a copy of theory 400 for testing purpose, right?

**Comment by felixhekhorn** [comment]
we need to address #47 first

**Comment by scarlehoff** [comment]
This has now been done. The default is no longer the 100 points and getting less points (like in theory 399) is also trivial.
