### ISSUE TITLE
Refactor `sub_scvar`

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineko#46]
in `sub_scvar` there is way to much repetition https://github.com/N3PDF/pineko/blob/9923b5c478b534d42036e3ce107d46a51619d0f7/src/pineko/cli/check.py#L48
reduce the prints to 1 or at most 2. Can be addressed in #25 or afterwards.

(just as a reminder: the other day you were wondering about the correct usage - so feel free to also update the doc string :upside_down_face:  )

**Comment by andreab1997** [comment]
I am not sure to have understood correctly: all the prints have a meaning, they are not just repetitions of the same concept. So I believe we want to have all of them, in such a way we can really understand what is missing (i.e. the renormalization scale variation for alpha_em rather than the factorization scale variation for alpha_s and so on). Have I misunderstood something?

**Comment by felixhekhorn** [comment]
okay, a bit more clearer: the reduce the number of prints in the code, but not in the output - they are all almost the same; some simple conditions and a loop should do the trick

**Comment by andreab1997** [comment]
Ah ok I see now :) 
After https://github.com/NNPDF/pineko/pull/25 I will do this

**Comment by AleCandido** [comment]
In a word: "deduplicate" :)
