### ISSUE TITLE
Make opcard template theory dependent

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineko#47]
A practical limitation is the current pineko design: because pineko currently assumes a global `operator_card_template`: https://github.com/NNPDF/pineko/blob/707f21fba8d3715b68cc6ad4371229db84acdded/pineko.debug.toml#L6
- which defines the `interpolation_xgrid` which is the internal grid used to compute all operators
- but it could even hold a `inputgrid`, which instead defines the grid exposed to the fit (consider that for eko input=fitting scale)
- I guess we should change this design to make the template theory dependent, i.e. scope it by the theory id as all the other stuff

_Originally posted by @felixhekhorn in https://github.com/NNPDF/pineko/issues/42#issuecomment-1227099523_

**Comment by AleCandido** [comment]
Since the `inputgrid` is not part of the theory database, then:
- either we add a field to the db, or
- we should add some theory metadata (in the stored folder on the server)

Otherwise it is a bit annoying this is not declared anywhere, and you should rely on the presence of some specific FkTable to check which xgrid is used for a given theory.
