### ISSUE TITLE
Fktables for NLO theory

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/pineko#62]
This is the NLO eqiuivalent of NNPDF/fktables#5 

We list here the Fktables which we cannot compute at the moment for the central NLO theory (208):
- jets (so needs https://github.com/N3PDF/eko/pull/105)
  - [ ] ATLAS_2JET_7TEV_R06
  - [ ] ATLAS_1JET_8TEV_R06
  - [ ] CMS_1JET_8TEV
  - [ ] CMS_2JET_7TEV
- missing grids
  - [x] ATLAS_WCHARM_WP_DIFF_7TEV (take from dom /media/Fk/fktables/data/appl_subgrids)
  - [x] ATLAS_WCHARM_WM_DIFF_7TEV (take from dom /media/Fk/fktables/data/appl_subgrids)
  - [x] CMSWCHARMTOT (Write the yamldb for the composition CMSWCHARM_WP and CMSWCHARM_WM with operand "add", take the two grids from /media/Fk/fktables/data/appl_subgrids )
  - [x] CMSWCHARMRAT (same of previous but with operands "ratio")
  - [x] CMS_WCHARM_DIFF_UNNORM_13TEV (same as the previous but with operand "add" and different grids: CMS_WCHARM_13TEV_WMC and CMS_WCHARM_13TEV_WPCB)
- We miss ren sv:
  - [ ] ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM (because we are missing ren sv for CMSTTBARTOT8TEV-TOPDIFF8TEVTOT, coming from Sherpa)
  - [ ] ATLAS_TTBARTOT_13TEV_FULLLUMI (because we are missing ren sv for ATLAS_TTBARTOT_13TEV_FULLLUMI-TOPDIFF13TEVTOT, coming from Sherpa)
  - [ ] ATLASTTBARTOT7TEV (because of ATLASTTBARTOT7TEV-TOPDIFF7TEVTOT, coming from Sherpa)
  - [ ] ATLASTTBARTOT8TEV (because of ATLASTTBARTOT8TEV-TOPDIFF8TEVTOT, this should be the same as CMSTTBARTOT8TEV-TOPDIFF8TEVTOT)
  - [ ] ATLAS_WM_JET_8TEV_PT ( because of ATLAS_WM_JET_8TEV_PT-atlas-atlas-wjets-arxiv-1711.03296-xsec003 which is coming from ploughshare)
  - [ ] ATLAS_WP_JET_8TEV_PT ( because of ATLAS_WP_JET_8TEV_PT-atlas-atlas-wjets-arxiv-1711.03296-xsec002 which is coming from ploughshare)
  - [ ] ATLASZPT8TEVMDIST (it is coming from MCFM)
  - [ ] ATLASZPT8TEVYDIST  (it is coming from MCFM)
  - [ ] CMS_1JET_8TEV (coming from NLOjet++)
  - [ ] CMSTOPDIFF8TEVTTRAPNORM (because of CMSTOPDIFF8TEVTTRAPNORM-TOPDIFF8TEVTTRAP, coming from Sherpa and total cross-section see above)
  - [ ] CMSTTBARTOT13TEV (because of CMSTTBARTOT13TEV-TOPDIFF13TEVTOT, coming from Sherpa)
  - [ ] CMSTTBARTOT8TEV (because of CMSTTBARTOT8TEV-TOPDIFF8TEVTOT, coming from Sherpa)
  - [ ] CMSTTBARTOT7TEV (because of CMSTTBARTOT7TEV-TOPDIFF7TEVTOT, coming from Sherpa)
  - [ ] CMSZDIFF12 (coming from MCFM)
  - [ ] ATLAS_WCHARM_WP_DIFF_7TEV 
  - [ ] ATLAS_WCHARM_WM_DIFF_7TEV 
  - [ ] CMSWCHARMTOT 
  - [ ] CMSWCHARMRAT 
  - [ ] CMS_WCHARM_DIFF_UNNORM_13TEV 
- FTDY (needs VRAP)
  - [x] DYE886R_dw_ite
  - [x] DYE886P
  - [x] DYE906R_dw_ite
- Things to check:
  - [x] D0ZRAP_40 (working for NNLO, check the bug)
  - [x] D0WMASY  
  - [x] ATLASWZRAP36PB
  - [x] ATLASDY2D8TEV
  - [x] ATLAS_DY_2D_8TEV_LOWMASS
  - [x] ATLASPHT15_SF (two bins for each FKtable are correct the others are not)
  - [x] CMSWEASY840PB
  - [x] CMSWMASY47FB
  - [x] CMSWMU8TEV
- Things with a conjectured solution
  - [x] ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM (maybe just a 2.0 conversion factor)
  - [x] ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM (same)
  - [x] CDFZRAP_NEW (see issue NNPDF/fktables#17)
  - [x] CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM (this is actually correct NNPDF/fktables#5 )

**Comment by cschwan** [comment]
fFor the renormalization scales:

- all top-pair production named `CMSTTBARTOT8TEV-TOPDIFF8TEVTOT` should be total cross sections and therefore called `ATLAS_TTB_{7,8,13}TEV_TOT`. If that's the case the scales are chosen dynamically (opposed to statically `mur = muf = Mt` in the old grids), so you might see differences. But I have to check to confirm all that.
- for `ATLAS_WM_JET_8TEV_PT` and `ATLAS_WP_JET_8TEV_PT` we have <https://github.com/NNPDF/runcards/pull/100>, so there are at least runcards, but I never uploaded the grids because the comparison with the old ones failed (see the linked Issue).
- for `ATLASZPT8TEVMDIST` and `ATLASZPT8TEVYDIST` we have <https://github.com/NNPDF/runcards/pull/61>, similar story as above.
- for jets we have runcards and it should be possible to run them for at least NLO QCD. I always tried with NLO QCD + NLO EW/mixed, but that's probably not a good idea. For this we should be able to generate grids!
- `CMSZDIFF12` this I never implemented, but we should be able to generate predictions
- W+charm is probably not possible at NLO without more work. But they're not needed for NNLO QCD.
