### ISSUE TITLE
Remove `fact_scale` even when using EXPONENTIATED

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/pineko#81]
Just to be sure, with the new implementation of scale variations methods in EKO we should also avoid the `fact_scale` argument that at the moment is used here https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L198

right? @felixhekhorn @AleCandido

**Comment by felixhekhorn** [comment]
yes, but in exchange we should adjust the threshold values https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L187
I'm a bit confused by this transformation https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L197
because I believe we should do the same on the thresholds - which however is in contradiction with the current implementation in eko https://github.com/NNPDF/eko/blob/935ad228c081fdf8a540c07b6435d5f413c5c9f4/src/eko/runner/legacy.py#L97-L103 ...

Actually, it might be sufficient to swap the condition here:
https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L156

**Comment by andreab1997** [comment]
> yes, but in exchange we should adjust the threshold values
> 
> https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L187
> 
You mean that if you want to also include resummation scale variations you need to move the thresholds, right? Otherwise they are fine as they are now.

> 
> I'm a bit confused by this transformation
> https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L197
> 
> 
> because I believe we should do the same on the thresholds - which however is in contradiction with the current implementation in eko https://github.com/NNPDF/eko/blob/935ad228c081fdf8a540c07b6435d5f413c5c9f4/src/eko/runner/legacy.py#L97-L103 ...
> Actually, it might be sufficient to swap the condition here:
> 
> https://github.com/NNPDF/pineko/blob/63af934791c9c7794c847513bc7d627f9db3405e/src/pineko/evolve.py#L156

For this, 

- for scheme B `muf2` should be the central scales and, at the moment, `xif = 1.0` so  `xir * xir * muf2 / xif / xif` would be the renormalization scale which is correct, right?
- for scheme C `muf2` are actually the factorization scales and instead `xif` is the real `xif` so  `xir * xir * muf2 / xif / xif` again would be the renormalization scale which is correct.
- for scheme A it should be same as scheme C

Do you agree or am I missing something?
